let suggestions = [
    "What is Space",
    "Why Space",
    "Space Is Vast",
    "What Is BlackHole",
    "What is Lunar And Solar Eclipse",
    "What will Happen When space would End",
    "Do alines exite in space",
    "What is saw alines",
    "I want to go to space",
    "Am I a good persone to go in space",
    "I want to go to mars",
    "Mars is great or not",
    "space force",
    "space",
    "space tool",
    "space force",
    "spaceX",
];
